import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AuroraBackground } from "../components/aurora-background";
import Navbar from "@/components/Navbar";
import Services from "@/components/Services";

import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Footer from "@/components/Footer";
import SecondSlider from "@/components/SecondSlider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar></Navbar>
        <AuroraBackground>{children}</AuroraBackground>
        <Services />
        <Skills />
        <SecondSlider />
        <Projects />

        <Footer />
      </body>
    </html>
  );
}
